apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapRoles: |
      rolearn: arn:aws:iam::320527135875:role/my-github-role
      username: github-ci
      groups:
        - system:masters 
  # mapUsers: | 
  #   - userarn: arn:aws:iam::320527135875:user/github-ci
  #     username: github-ci
  #     groups:
  #       - system:masters